esphome:
  name: lemon
  platform: ESP8266
  board: esp_wroom_02

captive_portal:

wifi:
  ssid: "Plankton"
  power_save_mode: NONE

status_led:
  pin:
    number: GPIO16
    inverted: True

debug:

logger:
  level: DEBUG

api:

ota:

sensor:
  - platform: adc
    pin: VCC
    name: "VCC"
