esphome:
  name: molgan
  platform: ESP8266
  board: d1_mini

  on_boot:
    priority: 10
    then:
      - light.turn_on:
          id: fastled
          effect: "Random Twinkle"
          brightness: 1.0
      - output.turn_on: gpio_d6
      - output.turn_off: gpio_d8

captive_portal:

wifi:
  ssid: !secret ssid
  password: !secret password
  ap:
    ssid: "Molgan"

ota:

logger:
  level: VERBOSE

api:

web_server:

light:
  - platform: fastled_clockless
    chipset: NEOPIXEL
    pin: D3
    num_leds: 16
    name: FastLED
    id: fastled
    gamma_correct: 2.0
    effects:
      - addressable_rainbow:
          name: Rainbow
      - random:
          name: Random
      - strobe:
          name: Strobe
      - flicker:
          name: Flicker
      - addressable_color_wipe:
          name: "Color Wipe"
      - addressable_scan:
          name: "Scan"
      - addressable_twinkle:
          name: "Twinkle"
      - addressable_random_twinkle:
          name: "Random Twinkle"
      - addressable_fireworks:
          name: "Fireworks"
      - addressable_flicker:
          name: "Addressable Flicker"

output:
  - platform: gpio
    pin: D6
    id: gpio_d6
  - platform: gpio
    pin: D8
    id: gpio_d8

dallas:
  - pin: D7

sensor:
  - platform: dallas
    index: 0
    id: board_temperature
    name: Temperature

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_rssi
    update_interval: 60s
